import { ref } from "vue";
import { defineStore } from "pinia";

export const useProductStore = defineStore("products", () => {
  const products = ref([
    {
      id: 899,
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 5,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: 900,
      name: "Termék hangzatos neve",
      price: 100.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "src/assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 5,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: 9001,
      name: "Termék hangzatos neve",
      price: 189.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 5,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 99.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 4,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 105.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 4,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Ital és ételtartók",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 4,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 4,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Fitnesz kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 4,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Sport eszközök",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 4,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Italok",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 3,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Sportszeletek",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 3,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Ital és ételtartók",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 3,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Táplálék kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 3,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Fitnesz kiegészítők",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 3,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Sport eszközök",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 2,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Italok",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 2,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Sportszeletek",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 2,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
    {
      id: Math.floor(Math.random() * 1000),
      name: "Termék hangzatos neve",
      price: 149.99,
      description: "Whey protein isolate drink powder with glutamine and BCAA",
      category: "Ital és ételtartók",
      src: "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      rating: 5,
      flavour: "vanilia",
      weight: "450g",
      galery: [
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
        "../../assets/images/csirke_rizs_shop-image2-removebg-preview.png",
      ],
    },
  ]);

  

  return { products };
});
